-- >>> MIGRATION 0014 — SEED (idempotent) ======================================

insert into spend_categories (slug, name, is_primary_chip, sort_order) values
  ('groceries','Groceries', true, 10),
  ('fuel','Fuel',           true, 20),
  ('dining','Dining',       true, 30),
  ('online','Online Shopping', true, 40),
  ('travel','Travel',       true, 50),
  ('bills','Bills & Utilities', true, 60),
  ('rent','Rent',           false, 70),
  ('insurance','Insurance', false, 80),
  ('education','Education', false, 90),
  ('government','Government', false, 100),
  ('wallet','Wallet Load',  false, 110),
  ('entertainment','Entertainment', false, 120),
  ('health','Health & Pharmacy', false, 130),
  ('other','Other',         false, 999)
on conflict (slug) do nothing;

insert into mcc_categories (mcc, description, category_id) values
  ('5411','Grocery Stores, Supermarkets', (select id from spend_categories where slug='groceries')),
  ('5541','Service Stations',             (select id from spend_categories where slug='fuel')),
  ('5542','Automated Fuel Dispensers',    (select id from spend_categories where slug='fuel')),
  ('5812','Eating Places, Restaurants',   (select id from spend_categories where slug='dining')),
  ('5814','Fast Food Restaurants',        (select id from spend_categories where slug='dining')),
  ('5999','Miscellaneous Retail',         (select id from spend_categories where slug='other')),
  ('4900','Utilities',                    (select id from spend_categories where slug='bills')),
  ('4511','Airlines',                     (select id from spend_categories where slug='travel')),
  ('7011','Lodging, Hotels',              (select id from spend_categories where slug='travel'))
on conflict (mcc) do nothing;
-- Full ISO 18245 seed is generated by scripts/seed_mcc.sql (DB-1.3).

insert into kill_switches (key, is_killed, reason) values
  ('recommendation_engine', false, null),
  ('geofence_notifications', false, null),
  ('crowdsource_ingest', false, null)
on conflict (key) do nothing;

insert into remote_config (key, value, description) values
  ('min_contribution_confirmations', '2'::jsonb, 'Publish gate N (§6.3)'),
  ('divergence_threshold_pct',       '0.15'::jsonb, 'Source B1 trigger'),
  ('contribution_daily_quota',       '50'::jsonb, 'Per-device rate limit'),
  ('notification_daily_cap',         '3'::jsonb, 'H3 frequency cap'),
  ('geofence_dwell_seconds',         '45'::jsonb, 'Debounce before notifying')
on conflict (key) do nothing;


